package types

import "errors"

var (
	ErrSpanTooSmall             = errors.New("span to write is too small")
	ErrValidation               = errors.New("wasm code does not pass basic validation")
	ErrDeserialization          = errors.New("fail to deserialize wasm into Partity-wasm module")
	ErrSerialization            = errors.New("fail to serialize Parity-wasm module into wasm")
	ErrInvalidImports           = errors.New("wasm code contains invalid import symbols")
	ErrInvalidExports           = errors.New("wasm code contains invalid export symbols")
	ErrBadMemorySection         = errors.New("wasm code contains bad memory sections")
	ErrGasCounterInjection      = errors.New("fail to inject gas counter into Wasm code")
	ErrStackHeightInjection     = errors.New("fail to inject stack height limit into Wasm code")
	ErrInstantiation            = errors.New("error while instantiating Wasm with resolvers")
	ErrRuntime                  = errors.New("runtime error while executing the Wasm script")
	ErrOutOfGas                 = errors.New("out-of-gas while executing the wasm script")
	ErrBadEntrySignature        = errors.New("bad execution entry point signature")
	ErrMemoryOutOfBound         = errors.New("out-of-bound memory access while executing the wasm script")
	ErrUninitializedContextData = errors.New("getting uninitialized context data while executing the wasm script")
	ErrChecksumLengthNotMatch   = errors.New("Checksum not of intended length while executing the wasm script")
	ErrDataLengthOutOfBound     = errors.New("Data length is out of bound while executing the wasm script")
	ErrConvertTypeOutOfBound    = errors.New("type out of bound while executing the wasm script")
	ErrWrongPeriodAction        = errors.New("OEI action to invoke is not available")
	ErrTooManyExternalData      = errors.New("too many external data requests")
	ErrDuplicateExternalID      = errors.New("wasm code asks data with duplicate external id")
	ErrBadValidatorIndex        = errors.New("bad validator index parameter")
	ErrBadExternalID            = errors.New("bad external ID parameter")
	ErrUnavailableExternalData  = errors.New("external data is not available")
	ErrRepeatSetReturnData      = errors.New("set return data is called more than once")
	ErrUnknown                  = errors.New("unknown error")
)
